kind: Service
apiVersion: v1
metadata:
  name: cadvisor
  namespace: cadvisor
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '8080'
spec:
  selector:
      app:
        cadvisor
  ports:
  - name: cadvisor
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: monitoring
spec:
  type: ExternalName
  externalName: cadvisor.cadvisor.svc.cluster.local
  ports:
  - port: 9100
    targetPort: 9100
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: default
spec:
  type: ExternalName
  externalName: cadvisor.cadvisor.svc.cluster.local
  ports:
  - port: 9100
    targetPort: 9100
    protocol: TCP